import type { Metadata } from "next";
import { Montserrat } from 'next/font/google'
import "./globals.css";
import { Nav } from "@/components/main/nav";
import Hero from "@/components/main/hero";
import Footer from "@/components/main/footer";
import { Toaster } from "@/components/ui/toaster";


const montserrat = Montserrat({
  weight: ['300', '500', '600'],
  style: ['italic', 'normal'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Psicologia y cultura",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={montserrat.className}
      >
        <Nav />
        <Hero />
        <main>{children}</main>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
